# Generated by Django 4.2.4 on 2023-08-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
