# Generated by Django 4.2.4 on 2023-08-10 06:36

from django.db import migrations, models
import rap.validator


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0004_alter_member_birth_date_alter_member_caste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Enter a valid 10-digit phone number or leave it blank.', null=True, validators=[rap.validator.validate_phone_number]),
        ),
    ]
