# Generated by Django 4.2.4 on 2023-08-10 06:51

from django.db import migrations, models
import rap.validator


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0005_alter_member_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='perm_wardno',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
    ]
