# Generated by Django 4.2.4 on 2023-08-10 07:07

from django.db import migrations, models
import rap.validator


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0006_alter_member_perm_wardno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='current_wardno',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='family_count',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_id',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='reg_number',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='voter_id',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='worktenure1',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='worktenure2',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='worktenure3',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
        migrations.AlterField(
            model_name='member',
            name='worktenure5',
            field=models.IntegerField(blank=True, null=True, validators=[rap.validator.validate_nullable_integer]),
        ),
    ]
