# Generated by Django 4.2.4 on 2023-08-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0007_alter_member_current_wardno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='reg_number',
            new_name='citizenship_number',
        ),
    ]
