# Generated by Django 4.2.4 on 2023-08-10 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0009_alter_member_citizenship_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_date',
        ),
    ]
