# Generated by Django 4.2.4 on 2023-08-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0010_remove_member_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='year_joined',
        ),
    ]
