# Generated by Django 4.2.4 on 2023-08-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0012_member_birth_date_member_membership_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='membership_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
