# Generated by Django 4.2.4 on 2023-08-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rap', '0014_alter_member_birth_date_alter_member_membership_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter a valid 10-digit phone number or leave it blank.', null=True),
        ),
    ]
